#!/bin/bash

if [[ $# -ne 2 ]]
    then
        echo "Error: script requires exactly 2 arguments" >&2
        exit 1
elif ! [[ "$1" =~ ^[-+]?(0|[1-9][0-9]{0,8})$ ]] || ! [[ "$2" =~ ^[-+]?(0|[1-9][0-9]{0,8})$ ]]
    then
        echo "Error: Both arguments must be integers with 9 or less digits (no leading 0s)" >&2
        exit 2
else
    if [[ $1 -lt $2 ]]
        then 
            echo "$1"
            exit 0
    elif [[ $2 -lt $1 ]]
        then
            echo "$2"
            exit 0
    else
        echo "Error: both arguments are the same" >&2
        exit 1
    fi
fi